In [1]:
#NAME:DHEEPIKA.I
#REG NO:21UAI023

In [2]:
#11
i=1
while i<=6:
    for j in range(1,i):
        print("*",end='\t')
    print(end='\n')
    i+=1


*	
*	*	
*	*	*	
*	*	*	*	
*	*	*	*	*	


In [3]:
#12
def remove_char(string, n):
    print("Original string:", string)
    a = string[n:]
    return string

print("Remove the characters from a string")
print(remove_char("Entertainment", 6))

Remove the characters from a string
Original string: Entertainment
Entertainment


In [4]:
#13
nums = []
for i in range(5):
    num=int(input("Enter the number"))
    nums.append(num)
    
for i in nums:
    if i%5 == 0:
        print(i)

Enter the number5
Enter the number15
Enter the number24
Enter the number42
Enter the number78
5
15


In [91]:
#14
strings=["hi","hi","hi","hello"]
count=strings.count("hi")

print(count)

3


In [19]:
#15
for i in range(6):
    for j in range(i):
        print(i,end='')
    print('')


1
22
333
4444
55555


In [21]:
#17.list
List = [35,78,15,69,97]
print("Initial List : ",List)
length = len(List)
temp = List[0]
List[0] = List[length - 1]
List[length - 1] = temp
print("List after Swapping : ", List)

Initial List :  [35, 78, 15, 69, 97]
List after Swapping :  [97, 78, 15, 69, 35]


In [31]:
#18.list
def swapPositions(list,pos1,pos2):
    
    list[pos1],List[pos2] = list[pos2],list[pos1]
    return list
 
List = [1,2,3,4
pos1,pos2  = 1,4
 
print(swapPositions(List, pos1-1, pos2-1))

[4, 2, 3, 1]


In [32]:
#19.list
mylist=[10,20,30,40,50,60]
len(mylist)

6

In [35]:
#21.list
def max(x,y):
    if x>y:
        return x
    else:
        return y
        
x=45
y=14
print(max(x,y))

45


In [36]:
#22.list
def min(x,y):
    if(x<y):
        return x
    else:
        return y
    
x=17
y=10
print(min(x,y))

10


In [38]:
#22.string
str="Dheepika"
half = int(len(str) / 2)
 
if len(str) % 2 == 0:  
    first_str = str[:half]
    second_str = str[half:]
else:  
    first_str = str[:half]
    second_str = str[half+1:]
if first_str == second_str:
    print(str,"String is symmetrical")
else:
    print(str,"String is not symmetrical")
if first_str == second_str[::-1]: 
    print(str,"String is palinadrome")
else:
    print(str,"String is not palimdrome")


Dheepika String is not symmetrical
Dheepika String is not palimdrome


In [45]:
#23.string
string = "My name is Dheepika"
s = string.split()[::-1]
l = []
for i in s:
   l.append(i)

print("".join(l))

DheepikaisnameMy


In [47]:
#24.string
str = "hello" 
print ("The original string is : " +str)
new_str = ""
for i in range(len(str)):
    if i != 2:
        new_str = new_str + str[i] 
print ("The string after removal of i'th character : " +new_str)

The original string is : hello
The string after removal of i'th character : helo


In [50]:
#27.tuple
tuple=('a','c','e','g','i')
print("Length of tuple : ",len(tuple))

Length of tuple :  5


In [40]:
#28.tuple
Tuple = (10, 15, 20, 25, 3, 89, 12, 45)
K = 2
sortedlist = sorted(list(Tuple))
vals = []
for i in range(K):
    vals.append(sortedlist[i])
    
for i in range((len(sortedlist) - K), len(sortedlist)):
    vals.append(sortedlist[i])

    
print("Tuple : ", str(Tuple))
print("K maximum and minimum values : ", str(vals))

Tuple :  (10, 15, 20, 25, 3, 89, 12, 45)
K maximum and minimum values :  [3, 10, 45, 89]


In [32]:
#29.tuple
Tuplen = (73, 59, 13, 86, 10, 28)
print("Tuple Items = ",Tuplen)
tupleSum = sum(Tuplen)
print("\nThe Sum of numTuple Tuple Items = ", tupleSum)

Tuple Items =  (73, 59, 13, 86, 10, 28)

The Sum of numTuple Tuple Items =  269


In [70]:
#32.dict
def dictionary():
    key_value = {}
    key_value[0] = 66
    key_value[1] = 11
    key_value[2] = 70
    key_value[3] = 24
    key_value[4] = 98
    key_value[5] = 37
    print("Task 1:\n")
    print("Key_value", key_value)
    for i in sorted(key_value.keys()):
        print(i, end=" ")
 
 
def main():
    
    dictionary()
if __name__ == "__main__":
    main()

Task 1:

Key_value {0: 66, 1: 11, 2: 70, 3: 24, 4: 98, 5: 37}
0 1 2 3 4 5 

In [92]:
#33.dict
import random as ran
dict = {}
x, y, z = 10,25,50
dict[x, y, z] = x+y-z;
x, y, z = 65,24,53
dict[x, y, z] = x+y-z;
print(dict)

{(10, 25, 50): -15, (65, 24, 53): 36}


In [75]:
#34.dict
def returnSum(myDict):
 
    list = []
    for i in myDict:
        list.append(myDict[i])
    fsum= sum(list)
 
    return fsum
dict = {'a':500, 'b':1900, 'c':840}
print("Sum :", returnSum(dict))

Sum : 3240


In [80]:
#36.set
set = {5, 10, 3, 15, 2, 20}
print("Original set elements:")
print(set)
print("\nSize of the set:")
print(len(set))


Original set elements:
{2, 3, 20, 5, 10, 15}

Size of the set:
6


In [81]:
#37.set
set={"apple","banana","cherry"}
for i in set:
    print(i)

banana
apple
cherry


In [88]:
#38.set
set=(65,63,58,82,76)
min_ele,max_ele=set[0],set[0] 
for i in range(1,len(set)):
    if set[i]<min_ele:
        min_ele=set[i]
    if set[i]>max_ele:
        max_ele=set[i]
print('Minimum Element in the list',set,'is',min_ele)
print('Maximum Element in the list',set,'is',max_ele)



Minimum Element in the list (65, 63, 58, 82, 76) is 58
Maximum Element in the list (65, 63, 58, 82, 76) is 82


In [90]:
#39.set
items={"chair","table","hammer","pillow"}
items.remove("hammer")
print(items)

{'chair', 'pillow', 'table'}


In [3]:
#42.matrix
import numpy as np
M = np.array([[56, 77], [13, 24]])
  
N = np.array([[64, 92], [27, 72]])
  
print("Print the elements of first matrix M:")
print(M)
print("Print the elements of second matrix N:")
print(N)
  
print("Addition of the two matrix")
print(np.add(M,N))
print("Subtraction of the matrix:")
print(np.subtract(M,N))

Print the elements of first matrix M:
[[56 77]
 [13 24]]
Print the elements of second matrix N:
[[64 92]
 [27 72]]
Addition of the two matrix
[[120 169]
 [ 40  96]]
Subtraction of the matrix:
[[ -8 -15]
 [-14 -48]]


In [7]:
#41.matrix
thelist = [[6, 2, 7], [5, 10, 11], [4, 6, 14], [8, 7, 3]]
print("The original list :" + str(thelist))
assign = {thelist[0][ele] :  thelist[ele + 1] for ele in range(len(thelist) -1)}
print("The Assigned Matrix :" + str(assign))

The original list :[[6, 2, 7], [5, 10, 11], [4, 6, 14], [8, 7, 3]]
The Assigned Matrix :{6: [5, 10, 11], 2: [4, 6, 14], 7: [8, 7, 3]}


In [17]:
#46.function
import inspect 
def f(a, b ,c):
    pass
a_signature = inspect.signature(f)
parameters = a_signature.parameters
parameterlist = list(parameters)
print(parameterlist)

['a', 'b', 'c']


In [24]:
#47.function
def ABC(name,dept,year):
    print("My name,dept and section is :" ,name , dept , year)
ABC ("Dheepika" ,"AI&DS" ,"1st year")

My name,dept and section is : Dheepika AI&DS 1st year
